# Generated by Django 2.2.11 on 2020-03-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(db_column='genre_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=250)),
                ('release_date', models.DateField()),
                ('name', models.CharField(max_length=250)),
                ('copyright', models.TextField()),
                ('url', models.URLField()),
                ('genre', models.ManyToManyField(related_name='genres', to='api.Genre')),
            ],
        ),
    ]
