# Generated by Django 2.2.11 on 2020-03-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200328_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='copyright',
            field=models.TextField(blank=True, null=True),
        ),
    ]
